[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/gizak/termui"
  version = "3.0.0"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[constraint]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.4"

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.12"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.0"

[[override]]
  name = "github.com/census-instrumentation/opencensus-proto"
  version = "v0.1.0"
